### ISSUE TITLE
Cannot add KVM cloud.

### ISSUE THREAD

**Issue by burnsjake** [mistio/mist-ce#1024]
I can log into my KVM hypervisors with my id_rsa private key. 

I upload the private key to the mist.io keys section.

I click add cloud, add the IP address of my hypervisor, select the private key, add my username.

When I click add cloud, I get the following:
Unauthorized cloud credentials: MachineUnauthorizedError("Couldn't authenticate to machine: Couldn't connect to deploy new SSH key.")

I have verified that I'm able to ssh directly to the hypervisor using a private key from my mist.io machine.

**Comment by d-mo** [comment]
Hi @burnsjake 
Sounds like a networking issue, possibly related to the Docker network. Is the IP addressable from the api container? You can test it using the following command
```
$ docker-compose exec api nc 10.42.0.147 22
SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.3
```
If you don't see an SSH header like the one above then it's a networking issue for sure.

Keep in mind that using localhost will not work.

If the problem persists try restarting the Docker daemon or even rebooting. Sometimes the iptables rules can get messed up.

**Comment by burnsjake** [comment]
I am able to connect from the api container via IP, hostname, and fully qualified domain name.

~/mistio$ docker-compose exec api sh
# nc 10.0.0.21 22
SSH-2.0-OpenSSH_8.8

I also changed the settings.py to be not localhost but the actual IP of my host and rebooted. No luck.

**Comment by d-mo** [comment]
That's very weird. Can you check the api logs while adding the KVM cloud?
```
docker-compose logs -f --tail 100 api
```
Also, is the user root or a passwordless sudoer? Some commands require root access and Mist will try to use sudo if the user is not root. Maybe it's hanging & timing out because sudo is expecting a password at this point?

**Comment by d-mo** [comment]
Can you try generating a new key pair through Mist and using it after appending the public key to your host's `~/.ssh/authorized_keys`?

We've seen some cases of key pairs that were not working well with libvirt for some reason. That issue was fixed some time ago. but it could be something similar.

Check this issue for more details. https://github.com/mistio/mist-ce/issues/954#issuecomment-530490951

**Comment by burnsjake** [comment]
Now my mist.io host just shows a blank page. did a docker-compose -v -rmi all --remove-orphans. Then did a docker network rm mistcenetworkhash .  

deleted the mistio directory that had docker-compose.yml. 

deleted all cookies in my browser and cache. 

re-downloaded docker-compose.yml, ran docker-compose up -d. Still getting a blank page..

I have tried using the IP, hostname, and FQDN, of my host in ~/mistio/settings/settings.py. Uncommented allow localhost and private networks. I cannot figure out why it worked a day ago and now it won't.

**Comment by burnsjake** [comment]
I was able to log in via firefox ESR. I still only get a blank page via brave or current firefox.

I generated a key via the mistCE interface. Added the pubkey section to my KVM hypervisor. Tried to add a KVM cloud and get the same problem. I copied the private key onto another host and verified that I am able to ssh into my kvm host as the correct user.

api_1                   | 2022-02-19 04:02:25,160 INFO  [mist.api.tasks][uWSGIWorker6Core0] Deleted periodic task: cloud:list_machines:978a6c124477463a870c20a5354eb18f
api_1                   | [pid: 70|app: 0|req: 8/29] 172.18.0.22 () {26 vars in 540 bytes} [Sat Feb 19 04:02:25 2022] GET /api/v1/clouds/978a6c124477463a870c20a5354eb18f/clusters?cached=True => generated 2 bytes in 9 msecs (HTTP/1.1 200) 2 headers in 70 bytes (1 switches on core 0)
api_1                   | [pid: 75|app: 0|req: 6/31] 172.18.0.22 () {26 vars in 534 bytes} [Sat Feb 19 04:02:25 2022] GET /api/v1/clouds/978a6c124477463a870c20a5354eb18f/sizes?cached=True => generated 2 bytes in 10 msecs (HTTP/1.1 200) 2 headers in 70 bytes (1 switches on core 0)
api_1                   | [pid: 59|app: 0|req: 3/31] 172.18.0.22 () {26 vars in 542 bytes} [Sat Feb 19 04:02:25 2022] GET /api/v1/clouds/978a6c124477463a870c20a5354eb18f/locations?cached=True => generated 176 bytes in 11 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
api_1                   | [pid: 60|app: 0|req: 3/32] 172.18.0.22 () {26 vars in 536 bytes} [Sat Feb 19 04:02:25 2022] GET /api/v1/clouds/978a6c124477463a870c20a5354eb18f/images?cached=True => generated 9404 bytes in 36 msecs (HTTP/1.1 200) 2 headers in 73 bytes (1 switches on core 0)
api_1                   | [pid: 64|app: 0|req: 3/33] 172.18.0.22 () {26 vars in 540 bytes} [Sat Feb 19 04:02:25 2022] GET /api/v1/clouds/978a6c124477463a870c20a5354eb18f/machines?cached=True => generated 46200 bytes in 105 msecs (HTTP/1.1 200) 2 headers in 74 bytes (1 switches on core 0)
api_1                   | [pid: 68|app: 0|req: 7/34] 172.18.0.25 () {44 vars in 1005 bytes} [Sat Feb 19 04:02:25 2022] POST /api/v1/clouds/978a6c124477463a870c20a5354eb18f => generated 2 bytes in 601 msecs (HTTP/1.0 200) 2 headers in 78 bytes (1 switches on core 0)
api_1                   | [pid: 68|app: 0|req: 8/35] 172.18.0.25 () {40 vars in 920 bytes} [Sat Feb 19 04:05:18 2022] GET /api/v1/keys/bd0ebd1a2e59437d9f20acb0eebadfd0/public => generated 382 bytes in 10 msecs (HTTP/1.0 200) 2 headers in 72 bytes (1 switches on core 0)
api_1                   | [pid: 62|app: 0|req: 3/36] 172.18.0.25 () {36 vars in 842 bytes} [Sat Feb 19 04:05:19 2022] GET /api/v1/logs?limit=50&filter=bd0ebd1a2e59437d9f20acb0eebadfd0 => generated 3502 bytes in 10 msecs (HTTP/1.0 200) 2 headers in 73 bytes (1 switches on core 0)
api_1                   | [pid: 68|app: 0|req: 9/37] 172.18.0.25 () {40 vars in 955 bytes} [Sat Feb 19 04:13:20 2022] GET /api/v1/keys/bd0ebd1a2e59437d9f20acb0eebadfd0/private => generated 1706 bytes in 15 msecs (HTTP/1.0 200) 2 headers in 73 bytes (1 switches on core 0)
api_1                   | 2022-02-19 04:15:45,475 INFO  [mist.api.clouds.methods][uWSGIWorker7Core0] Adding new cloud in provider 'libvirt'
api_1                   | 2022-02-19 04:15:45,479 WARNI [mist.api.helpers][uWSGIWorker7Core0] Got param 'machine_hostname' when expecting 'host', transforming.
api_1                   | 2022-02-19 04:15:45,479 WARNI [mist.api.helpers][uWSGIWorker7Core0] Got param 'machine_name' when expecting 'alias', transforming.
api_1                   | 2022-02-19 04:15:45,479 WARNI [mist.api.helpers][uWSGIWorker7Core0] Got param 'machine_user' when expecting 'username', transforming.
api_1                   | 2022-02-19 04:15:45,479 WARNI [mist.api.helpers][uWSGIWorker7Core0] Got param 'machine_key' when expecting 'key', transforming.
api_1                   | 2022-02-19 04:15:45,479 WARNI [mist.api.helpers][uWSGIWorker7Core0] Got param 'ssh_port' when expecting 'port', transforming.
api_1                   | 2022-02-19 04:15:45,496 INFO  [mist.api.keys.base][uWSGIWorker7Core0] Associating key bd0ebd1a2e59437d9f20acb0eebadfd0 to machine 10-0-0-21
api_1                   | [pid: 68|app: 0|req: 10/38] 172.18.0.22 () {26 vars in 429 bytes} [Sat Feb 19 04:15:45 2022] GET /api/v1/keys => generated 416 bytes in 10 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
api_1                   | 2022-02-19 04:15:46,012 INFO  [mist.api.keys.controllers][uWSGIWorker7Core0] Deploying key to host 10.0.0.21
api_1                   | 2022-02-19 04:15:46,026 INFO  [mist.api.shell][uWSGIWorker7Core0] autoconfiguring Shell for machine dddb2ee67daf4f9fa04968bc7de2d7c1:991237a42efd4b95bf2bb3498895a374
api_1                   | 2022-02-19 04:15:46,034 INFO  [mist.api.shell][uWSGIWorker7Core0] Got cloud & machine: 1 key associations
api_1                   | 2022-02-19 04:15:46,035 INFO  [mist.api.shell][uWSGIWorker7Core0] Got keys 1
api_1                   | 2022-02-19 04:15:46,036 INFO  [mist.api.shell][uWSGIWorker7Core0] Got users:['kvmuser']
api_1                   | 2022-02-19 04:15:46,036 INFO  [mist.api.shell][uWSGIWorker7Core0] Got ports:[22]
api_1                   | 2022-02-19 04:15:46,036 INFO  [mist.api.shell][uWSGIWorker7Core0] ssh -i mistio kvmuser@10.0.0.21:22
api_1                   | 2022-02-19 04:15:46,063 INFO  [paramiko.transport][Thread-6] Connected (version 2.0, client OpenSSH_8.8)
api_1                   | 2022-02-19 04:15:46,109 INFO  [paramiko.transport][Thread-6] Authentication (publickey) failed.
api_1                   | 2022-02-19 04:15:46,110 ERROR [mist.api.shell][uWSGIWorker7Core0] ssh exception AuthenticationException('Authentication failed.')
api_1                   | 2022-02-19 04:15:46,112 INFO  [mist.api.shell][uWSGIWorker7Core0] autoconfiguring Shell for machine dddb2ee67daf4f9fa04968bc7de2d7c1:991237a42efd4b95bf2bb3498895a374
api_1                   | 2022-02-19 04:15:46,115 INFO  [mist.api.shell][uWSGIWorker7Core0] Got cloud & machine: 1 key associations
api_1                   | 2022-02-19 04:15:46,116 INFO  [mist.api.shell][uWSGIWorker7Core0] Got key
api_1                   | 2022-02-19 04:15:46,116 INFO  [mist.api.shell][uWSGIWorker7Core0] Got users:['kvmuser']
api_1                   | 2022-02-19 04:15:46,116 INFO  [mist.api.shell][uWSGIWorker7Core0] Got ports:[22]
api_1                   | 2022-02-19 04:15:46,116 INFO  [mist.api.shell][uWSGIWorker7Core0] ssh -i mistio kvmuser@10.0.0.21:22
api_1                   | 2022-02-19 04:15:46,143 INFO  [paramiko.transport][Thread-8] Connected (version 2.0, client OpenSSH_8.8)
api_1                   | 2022-02-19 04:15:46,184 INFO  [paramiko.transport][Thread-8] Authentication (publickey) failed.
api_1                   | 2022-02-19 04:15:46,184 ERROR [mist.api.shell][uWSGIWorker7Core0] ssh exception AuthenticationException('Authentication failed.')
api_1                   | 2022-02-19 04:15:46,185 INFO  [mist.api.keys.base][uWSGIWorker7Core0] Disassociating key of machine '10-0-0-21'
api_1                   | 2022-02-19 04:15:46,208 INFO  [mist.api.shell][uWSGIWorker7Core0] Closing ssh connection to 10.0.0.21
api_1                   | [pid: 68|app: 0|req: 11/39] 172.18.0.22 () {26 vars in 429 bytes} [Sat Feb 19 04:15:46 2022] GET /api/v1/keys => generated 207 bytes in 11 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
api_1                   | 2022-02-19 04:15:46,712 ERROR [mist.api.clouds.controllers.main.controllers][uWSGIWorker7Core0] Could not connect to host 10.0.0.21.
api_1                   | 2022-02-19 04:15:46,783 INFO  [mist.api.views][uWSGIWorker7Core0] MistError: CloudUnauthorizedError('Unauthorized cloud credentials: MachineUnauthorizedError("Couldn\'t authenticate to machine: Couldn\'t connect to deploy new SSH key.")')
api_1                   | [pid: 70|app: 0|req: 9/40] 172.18.0.25 () {44 vars in 911 bytes} [Sat Feb 19 04:15:45 2022] POST /api/v1/clouds => generated 133 bytes in 1321 msecs (HTTP/1.0 401) 2 headers in 90 bytes (1 switches on core 0)

**Comment by d-mo** [comment]
This is getting weirder. I'm afraid I don't have a clue what's wrong and I cannot replicate the issue locally. I'd be happy to look into it if you can somehow provide access.

I would do something like the following
1. connect to the api container (`docker-compose exec api bash`)
2. edit /mist.api/src/mist/api/shell.py to add a traceback (`import ipdb;ipdb.set_trace()`) somewhere around line 298
3. reload the api server with `kill -HUP 1`
4. exit from the api container shell
5. attach to the api container: `docker attach `docker ps |grep api_|cut -f1 -d ' '``
6. try adding the cloud once again, which should drop the above command to the interactive python debugger
7. execute the code line by line using the debugger commands 'n', 's' & 'c', trying to figure out what's wrong

The blank page on Brave also does not make any sense to me. I would clear the browser cache, restart nginx just in case with `docker-compose restart nginx` and I would tail the api log while hitting the page to look for errors.

I hope that helps.

**Comment by Ciros55** [comment]
i have the same issue
i tried on multiple KVM hosts (Oracle Linux 8 , Fedora 35 , Debian 10, Manjaro Linux)
i tried install mistio on Ubuntu 22.04 LTS, Ubuntu 21.10 ,Ubuntu 20.04 LTS, Debian 10.

`api_1                   | 2022-05-11 10:16:58,280 INFO  [mist.api.clouds.methods][uWSGIWorker7Core0] Adding new cloud in provider 'libvirt'
api_1                   | 2022-05-11 10:16:58,285 WARNI [mist.api.helpers][uWSGIWorker7Core0] Got param 'machine_hostname' when expecting 'host', transforming.
api_1                   | 2022-05-11 10:16:58,286 WARNI [mist.api.helpers][uWSGIWorker7Core0] Got param 'machine_name' when expecting 'alias', transforming.
api_1                   | 2022-05-11 10:16:58,287 WARNI [mist.api.helpers][uWSGIWorker7Core0] Got param 'machine_user' when expecting 'username', transforming.
api_1                   | 2022-05-11 10:16:58,287 WARNI [mist.api.helpers][uWSGIWorker7Core0] Got param 'machine_key' when expecting 'key', transforming.
api_1                   | 2022-05-11 10:16:58,289 WARNI [mist.api.helpers][uWSGIWorker7Core0] Got param 'ssh_port' when expecting 'port', transforming.
api_1                   | 2022-05-11 10:16:58,303 INFO  [mist.api.keys.base][uWSGIWorker7Core0] Associating key db94071f7ca94cdc984c6bb672e1d6a3 to machine 12-0-0-4
api_1                   | [pid: 42|app: 0|req: 5/57] 172.18.0.10 () {26 vars in 429 bytes} [Wed May 11 10:16:58 2022] GET /api/v1/keys => generated 1026 bytes in 19 msecs (HTTP/1.1 200) 2 headers in 73 bytes (1 switches on core 0)
api_1                   | 2022-05-11 10:16:58,820 INFO  [mist.api.keys.controllers][uWSGIWorker7Core0] Deploying key to host 12.0.0.4
api_1                   | 2022-05-11 10:16:58,824 INFO  [mist.api.shell][uWSGIWorker7Core0] autoconfiguring Shell for machine 2a9732098e4347559f3aef872a5d361c:6bfb7dec0a6e4c598b4ccc9e2a568cb3
api_1                   | 2022-05-11 10:16:58,827 INFO  [mist.api.shell][uWSGIWorker7Core0] Got cloud & machine: 1 key associations
api_1                   | 2022-05-11 10:16:58,828 INFO  [mist.api.shell][uWSGIWorker7Core0] Got keys 1
api_1                   | 2022-05-11 10:16:58,829 INFO  [mist.api.shell][uWSGIWorker7Core0] Got users:['root']
api_1                   | 2022-05-11 10:16:58,829 INFO  [mist.api.shell][uWSGIWorker7Core0] Got ports:[22]
api_1                   | 2022-05-11 10:16:58,829 INFO  [mist.api.shell][uWSGIWorker7Core0] ssh -i ol8 root@12.0.0.4:22
api_1                   | 2022-05-11 10:16:58,852 INFO  [paramiko.transport][Thread-22] Connected (version 2.0, client OpenSSH_8.0)
api_1                   | 2022-05-11 10:16:58,873 INFO  [paramiko.transport][Thread-22] Authentication (publickey) failed.
api_1                   | 2022-05-11 10:16:58,873 ERROR [mist.api.shell][uWSGIWorker7Core0] ssh exception AuthenticationException('Authentication failed.')
api_1                   | 2022-05-11 10:16:58,876 INFO  [mist.api.shell][uWSGIWorker7Core0] autoconfiguring Shell for machine 2a9732098e4347559f3aef872a5d361c:6bfb7dec0a6e4c598b4ccc9e2a568cb3
api_1                   | 2022-05-11 10:16:58,879 INFO  [mist.api.shell][uWSGIWorker7Core0] Got cloud & machine: 1 key associations
api_1                   | 2022-05-11 10:16:58,880 INFO  [mist.api.shell][uWSGIWorker7Core0] Got key
api_1                   | 2022-05-11 10:16:58,881 INFO  [mist.api.shell][uWSGIWorker7Core0] Got users:['root']
api_1                   | 2022-05-11 10:16:58,881 INFO  [mist.api.shell][uWSGIWorker7Core0] Got ports:[22]
api_1                   | 2022-05-11 10:16:58,881 INFO  [mist.api.shell][uWSGIWorker7Core0] ssh -i ol8 root@12.0.0.4:22
api_1                   | 2022-05-11 10:16:58,902 INFO  [paramiko.transport][Thread-24] Connected (version 2.0, client OpenSSH_8.0)
api_1                   | 2022-05-11 10:16:58,922 INFO  [paramiko.transport][Thread-24] Authentication (publickey) failed.
api_1                   | 2022-05-11 10:16:58,922 ERROR [mist.api.shell][uWSGIWorker7Core0] ssh exception AuthenticationException('Authentication failed.')
api_1                   | 2022-05-11 10:16:58,923 INFO  [mist.api.keys.base][uWSGIWorker7Core0] Disassociating key of machine '12-0-0-4'
api_1                   | 2022-05-11 10:16:58,933 INFO  [mist.api.shell][uWSGIWorker7Core0] Closing ssh connection to 12.0.0.4
api_1                   | [pid: 43|app: 0|req: 8/58] 172.18.0.10 () {26 vars in 429 bytes} [Wed May 11 10:16:58 2022] GET /api/v1/keys => generated 819 bytes in 13 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
api_1                   | 2022-05-11 10:16:59,442 ERROR [mist.api.clouds.controllers.main.controllers][uWSGIWorker7Core0] Could not connect to host 12.0.0.4.
api_1                   | 2022-05-11 10:16:59,476 INFO  [mist.api.views][uWSGIWorker7Core0] MistError: CloudUnauthorizedError('Unauthorized cloud credentials: MachineUnauthorizedError("Couldn\'t authenticate to machine: Couldn\'t connect to deploy new SSH key.")')
api_1                   | [pid: 45|app: 0|req: 11/59] 172.18.0.20 () {46 vars in 992 bytes} [Wed May 11 10:16:58 2022] POST /api/v1/clouds => generated 133 bytes in 1210 msecs (HTTP/1.0 401) 2 headers in 90 bytes (1 switches on core 0)`

**Comment by cpsaltis** [comment]
Hi @Ciros55,

From: 

```
api_1 | 2022-05-11 10:16:58,881 INFO [mist.api.shell][uWSGIWorker7Core0] ssh -i ol8 root@12.0.0.4:22
api_1 | 2022-05-11 10:16:58,902 INFO [paramiko.transport][Thread-24] Connected (version 2.0, client OpenSSH_8.0)
api_1 | 2022-05-11 10:16:58,922 INFO [paramiko.transport][Thread-24] Authentication (publickey) failed.
```

It seems this is a key issue and unrelated to the previous discussion above.

Could you please try to connect from somewhere to your KVM host with `ssh -i ol8 root@12.0.0.4:22`?

If my assumption is correct, it will not work. To solve this problem make sure the SSH key you give to Mist when you add a KVM cloud is indeed in your KVM host.
